spring:
  profiles:
    active: default,slack

  devtools:
    remote:
      secret: secret-to-be-overridden

  data:
    neo4j:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
      uri: bolt://neo4j

rtmUrl: https://slack.com/api/rtm.start?token={token}&simple_latest&no_unreads
slackBotToken: ${SLACK_BOT_TOKEN}