spring:
  profiles:
    active: default,slack

  devtools:
    remote:
      secret: secret-to-be-overridden

rtmUrl: https://slack.com/api/rtm.start?token={token}&simple_latest&no_unreads
slackBotToken: ${SLACK_BOT_TOKEN}